/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as FlashcardsNewRouteImport } from './routes/flashcards.new'
import { Route as FlashcardsSetIdEditRouteImport } from './routes/flashcards.$setId.edit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CanvaConnectedRouteImport } from './routes/canva-connected'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as InvitationsTokenAcceptRouteImport } from './routes/invitations.$token.accept'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsNewRoute = FlashcardsNewRouteImport.update({
  id: '/flashcards/new',
  path: '/flashcards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsSetIdEditRoute = FlashcardsSetIdEditRouteImport.update({
  id: '/flashcards/$setId/edit',
  path: '/flashcards/$setId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvaConnectedRoute = CanvaConnectedRouteImport.update({
  id: '/canva-connected',
  path: '/canva-connected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenAcceptRoute = InvitationsTokenAcceptRouteImport.update({
  id: '/$token/accept',
  path: '/$token/accept',
  getParentRoute: () => InvitationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/canva-connected': typeof CanvaConnectedRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/flashcards/new': typeof FlashcardsNewRoute
  '/flashcards/$setId/edit': typeof FlashcardsSetIdEditRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/groups/': typeof GroupsIndexRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/canva-connected': typeof CanvaConnectedRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/flashcards/new': typeof FlashcardsNewRoute
  '/flashcards/$setId/edit': typeof FlashcardsSetIdEditRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/groups': typeof GroupsIndexRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/canva-connected': typeof CanvaConnectedRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/flashcards/new': typeof FlashcardsNewRoute
  '/flashcards/$setId/edit': typeof FlashcardsSetIdEditRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/groups/': typeof GroupsIndexRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/canva-connected'
    | '/dashboard'
    | '/flashcards'
    | '/flashcards/new'
    | '/flashcards/$setId/edit'
    | '/invitations'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/groups/$groupId'
    | '/login/callback'
    | '/groups/'
    | '/invitations/$token/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/canva-connected'
    | '/dashboard'
    | '/flashcards'
    | '/flashcards/new'
    | '/flashcards/$setId/edit'
    | '/invitations'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/groups/$groupId'
    | '/login/callback'
    | '/groups'
    | '/invitations/$token/accept'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/canva-connected'
    | '/dashboard'
    | '/flashcards'
    | '/flashcards/new'
    | '/flashcards/$setId/edit'
    | '/invitations'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/groups/$groupId'
    | '/login/callback'
    | '/groups/'
    | '/invitations/$token/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CanvaConnectedRoute: typeof CanvaConnectedRoute
  DashboardRoute: typeof DashboardRoute
  FlashcardsRoute: typeof FlashcardsRoute
  FlashcardsNewRoute: typeof FlashcardsNewRoute
  FlashcardsSetIdEditRoute: typeof FlashcardsSetIdEditRoute
  InvitationsRoute: typeof InvitationsRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/new': {
      id: '/flashcards/new'
      path: '/flashcards/new'
      fullPath: '/flashcards/new'
      preLoaderRoute: typeof FlashcardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/$setId/edit': {
      id: '/flashcards/$setId/edit'
      path: '/flashcards/$setId/edit'
      fullPath: '/flashcards/$setId/edit'
      preLoaderRoute: typeof FlashcardsSetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canva-connected': {
      id: '/canva-connected'
      path: '/canva-connected'
      fullPath: '/canva-connected'
      preLoaderRoute: typeof CanvaConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/accept': {
      id: '/invitations/$token/accept'
      path: '/$token/accept'
      fullPath: '/invitations/$token/accept'
      preLoaderRoute: typeof InvitationsTokenAcceptRouteImport
      parentRoute: typeof InvitationsRoute
    }
  }
}

interface InvitationsRouteChildren {
  InvitationsTokenAcceptRoute: typeof InvitationsTokenAcceptRoute
}

const InvitationsRouteChildren: InvitationsRouteChildren = {
  InvitationsTokenAcceptRoute: InvitationsTokenAcceptRoute,
}

const InvitationsRouteWithChildren = InvitationsRoute._addFileChildren(
  InvitationsRouteChildren,
)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CanvaConnectedRoute: CanvaConnectedRoute,
  DashboardRoute: DashboardRoute,
  FlashcardsRoute: FlashcardsRoute,
  FlashcardsNewRoute: FlashcardsNewRoute,
  FlashcardsSetIdEditRoute: FlashcardsSetIdEditRoute,
  InvitationsRoute: InvitationsRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
